import { useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowUp, ImagePlus, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Chapter = { title: string; text: string };
type Book = { id: number; title: string; author: string | null; description: string | null; language: string; chapters: string | null; coverUrl: string | null; manuscriptText: string };

export default function EditorialEditor({ book, onSaved }: { book: Book; onSaved: () => void }) {
  const initial = useMemo<Chapter[]>(() => { try { if (book.chapters) return JSON.parse(book.chapters); } catch {} return [{ title: book.title, text: book.manuscriptText }]; }, [book.chapters, book.manuscriptText, book.title]);
  const [author, setAuthor] = useState(book.author ?? ""); const [description, setDescription] = useState(book.description ?? ""); const [language, setLanguage] = useState(book.language || "pt-BR"); const [chapters, setChapters] = useState(initial); const [coverData, setCoverData] = useState<string>(); const [coverMimeType, setCoverMimeType] = useState<"image/jpeg" | "image/png">(); const coverRef = useRef<HTMLInputElement>(null);
  const save = trpc.books.updateEditorial.useMutation({ onSuccess: () => { toast.success("Preparação editorial salva."); onSaved(); }, onError: error => toast.error(error.message) });
  async function chooseCover(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const buffer = await file.arrayBuffer(); setCoverData(btoa(String.fromCharCode(...Array.from(new Uint8Array(buffer))))); setCoverMimeType(file.type === "image/png" ? "image/png" : "image/jpeg"); }
  function move(index: number, direction: -1 | 1) { const next = [...chapters]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setChapters(next); }
  return <div className="mt-8 rounded-2xl border border-[#e7e1d8] bg-[#f7f2eb] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a69b8d]">Mesa de preparação</p><h3 className="mt-1 font-serif text-xl font-semibold">Capa e capítulos</h3></div><Button onClick={() => save.mutate({ bookId: book.id, author, description, language, chapters, coverData, coverMimeType })} disabled={save.isPending} className="rounded-xl bg-[#292723] text-white"><Save size={15} className="mr-2"/>{save.isPending ? "Salvando..." : "Salvar"}</Button></div><div className="mt-5 grid gap-5 lg:grid-cols-[180px_1fr]"><div><button type="button" onClick={() => coverRef.current?.click()} className="group relative aspect-[2/3] w-full overflow-hidden rounded-xl border border-[#d9caba] bg-[#e8dfd2] text-[#92745c]">{coverData || book.coverUrl ? <img src={coverData ? `data:${coverMimeType};base64,${coverData}` : book.coverUrl!} alt="Pré-visualização da capa" className="h-full w-full object-cover"/> : <span className="flex h-full flex-col items-center justify-center gap-2 text-xs"><ImagePlus size={22}/><span>Adicionar capa</span></span>}</button><input ref={coverRef} type="file" accept="image/jpeg,image/png" onChange={chooseCover} className="hidden"/></div><div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Input value={author} onChange={e => setAuthor(e.target.value)} placeholder="Autor" className="border-[#d6c9b9] bg-white"/><Input value={language} onChange={e => setLanguage(e.target.value)} placeholder="Idioma (ex.: pt-BR)" className="border-[#d6c9b9] bg-white"/></div><Textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Descrição para a ficha editorial" className="min-h-[85px] border-[#d6c9b9] bg-white"/><div className="space-y-2">{chapters.map((chapter, index) => <div key={`${index}-${chapter.title}`} className="rounded-xl border border-[#ded2c4] bg-white p-3"><div className="flex items-center gap-2"><Input value={chapter.title} onChange={e => setChapters(chapters.map((item, i) => i === index ? { ...item, title: e.target.value } : item))} className="border-[#e6ddd3] font-serif"/><Button variant="ghost" size="icon" onClick={() => move(index, -1)} disabled={index === 0} aria-label="Mover capítulo para cima"><ArrowUp size={15}/></Button><Button variant="ghost" size="icon" onClick={() => move(index, 1)} disabled={index === chapters.length - 1} aria-label="Mover capítulo para baixo"><ArrowDown size={15}/></Button></div><Textarea value={chapter.text} onChange={e => setChapters(chapters.map((item, i) => i === index ? { ...item, text: e.target.value } : item))} className="mt-2 min-h-[70px] border-[#eee7df] text-sm"/></div>)}</div></div></div></div>;
}
