import { useState } from "react";
import { ChevronRight, FileText } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Version = { id: number; kind: string; filename: string; fileUrl: string; versionNumber: number; createdAt: Date };
const labels: Record<string, string> = { manuscript: "DOCX revisado", pdf: "PDF revisado", epub: "EPUB revisado", report: "Relatório" };

export default function VersionHistoryPanel({ bookId, versions }: { bookId: number; versions: Version[] }) {
  const [toId, setToId] = useState<number | undefined>(versions[0]?.id);
  const [fromId, setFromId] = useState<number | null>(null);
  const comparison = trpc.books.compareVersions.useQuery({ bookId, fromVersionId: fromId, toVersionId: toId ?? 0 }, { enabled: !!toId });
  return <div className="mt-8 rounded-2xl border border-[#e7e1d8] bg-[#fbfaf8] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#a69b8d]">Arquivo e histórico</p><h3 className="mt-1 font-serif text-xl font-semibold">Versões geradas</h3></div><span className="text-xs text-[#9d9184]">{versions.length} artefatos</span></div>{versions.length ? <><div className="mt-4 grid gap-2 md:grid-cols-2">{versions.map(version => <a key={version.id} href={version.fileUrl} download className="flex items-center gap-3 rounded-xl border border-[#e9e1d8] bg-white p-3 hover:border-[#b36f4d]"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#eee8de] text-[#9a7256]"><FileText size={15}/></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">V{version.versionNumber} · {labels[version.kind] ?? version.kind}</p><p className="truncate text-xs text-[#9a9085]">{version.filename}</p></div><ChevronRight size={14} className="text-[#b7aa9b}"/></a>)}</div><div className="mt-5 rounded-xl border border-[#e1d8cc] bg-white p-4"><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-semibold text-[#675e54]">Comparar <select value={fromId ?? "original"} onChange={event => setFromId(event.target.value === "original" ? null : Number(event.target.value))} className="ml-2 rounded-lg border border-[#ddd2c5] bg-[#fffdf8] px-2 py-1"><option value="original">Original</option>{versions.map(v => <option key={v.id} value={v.id}>V{v.versionNumber} · {labels[v.kind]}</option>)}</select></label><span className="text-xs text-[#a09589]">com</span><select value={toId ?? ""} onChange={event => setToId(Number(event.target.value))} className="rounded-lg border border-[#ddd2c5] bg-[#fffdf8] px-2 py-1 text-xs"><option value="">Selecione uma versão</option>{versions.map(v => <option key={v.id} value={v.id}>V{v.versionNumber} · {labels[v.kind]}</option>)}</select></div>{comparison.data && <div className="mt-4 max-h-72 overflow-auto rounded-lg bg-[#f7f3ed] p-3 font-mono text-xs leading-relaxed">{comparison.data.segments.map((segment, index) => <div key={index} className={segment.type === "added" ? "bg-[#dceee1] text-[#315d42]" : segment.type === "removed" ? "bg-[#f4dddd] text-[#8b3f3f] line-through" : "text-[#6d655d]"}>{segment.type === "added" ? "+ " : segment.type === "removed" ? "− " : "  "}{segment.text || " "}</div>)}</div>}</div></> : <p className="mt-4 text-sm text-[#8a8075]">Gere sua primeira versão revisada para começar o histórico.</p>}</div>;
}
